# Generated by Django 5.0.6 on 2024-06-07 00:09

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerName', models.CharField(max_length=100)),
                ('puuid', models.CharField(max_length=100)),
                ('tier', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('leaguePoints', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('level', models.IntegerField()),
                ('icon', models.IntegerField()),
                ('past_matches', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100)),
                ('game_length', models.IntegerField()),
                ('game_mode', models.IntegerField(max_length=100)),
                ('player_data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
