# Generated by Django 5.0.6 on 2024-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayStats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='riotID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='matches',
            name='game_mode',
            field=models.IntegerField(),
        ),
    ]
