# Generated by Django 5.0.6 on 2024-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayStats', '0002_accounts_riotid_alter_matches_game_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='game_time',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matches',
            name='game_length',
            field=models.CharField(max_length=100),
        ),
    ]
