# Generated by Django 5.0.6 on 2024-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayStats', '0003_matches_game_time_alter_matches_game_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='game_mode',
            field=models.CharField(max_length=100),
        ),
    ]
